TEST actions status check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,7 +27,9 @@ jobs:
       - name: Validate
         shell: bash
         run: |
-          if [${{ github.event.inputs.bump-type }} != 'beta'] && [${{ github.event.inputs.bump-type }} != 'bug'] && [${{ github.event.inputs.bump-type }} != 'feature'] && [${{ github.event.inputs.bump-type }} != 'major']; then exit 1;
+          if [${{ github.event.inputs.bump-type }} != 'beta'] && [${{ github.event.inputs.bump-type }} != 'bug'] && [${{ github.event.inputs.bump-type }} != 'feature'] && [${{ github.event.inputs.bump-type }} != 'major']; then
+            echo "Error on input bump-type, posible values are major, feature, bug and beta"
+            exit 1
 
       - name: 'Get Previous tag'
         id: previoustag
