TEST actions status check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,8 +28,8 @@ jobs:
         shell: bash
         run: |
           if ["${{ github.event.inputs.bump-type }}" != "beta"] && ["${{ github.event.inputs.bump-type }}" != "bug"] && ["${{ github.event.inputs.bump-type }}" != "feature"] && ["${{ github.event.inputs.bump-type }}" != "major"]; then
-            echo "Error on input bump-type, posible values are major, feature, bug and beta"
-            exit 1
+            echo "Error on input bump-type, posible values are major, feature, bug and beta";
+            exit 1;
 
       - name: 'Get Previous tag'
         id: previoustag
